// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Distraction Dodge",
    platforms: [
        .iOS("18.0")
    ],
    products: [
        .iOSApplication(
            name: "Distraction Dodge",
            targets: ["AppModule"],
            bundleIdentifier: "com.thisisayushs.DistractionDodge",
            teamIdentifier: "545HU3XVX3",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.mint),
            supportedDeviceFamilies: [
                .pad
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "Distraction Dodge uses the camera to track your eye movements and determine your focus area, helping you improve attention.")
            ],
            appCategory: .productivity
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)
